### ISSUE TITLE
Rewrite name and bin key

### ISSUE THREAD

**Issue by peterennis** [wintercounter/mhy#13]
Where is name and bin key?
What do you mean by rewrite?
What do you mean by link?

Are you using cmd on Windows? PowerShell? Other?

![Capture531](https://user-images.githubusercontent.com/140737/54502895-1e55d700-48ea-11e9-961a-a780667a9f09.png)

**Comment by wintercounter** [comment]
In mhy's `package.json`
Rewrite => Change the value to something else.
https://docs.npmjs.com/cli/link.html

I'm using `cmd` mostly on WIndows.

Well noted that that part of the docs isn't clear enough, I'll update it soon, thanks for the report.
