### ISSUE TITLE
Depth flag for config output

### ISSUE THREAD

**Issue by FabianLauer** [wintercounter/mhy#20]
When running `/mhy config typescript`, I get the following output:

```js
{ compilerOptions:
   { module: 'esNext',
     target: 'esnext',
     moduleResolution: 'node',
     allowJs: false,
     emitDeclarationOnly: true,
     strict: true,
     jsx: 'preserve',
     resolveJsonModule: true,
     esModuleInterop: true,
     noImplicitAny: false,
     declaration: true,
     baseUrl: '/path/redacted',
     skipLibCheck: true,
     incremental: true,
     outDir: 'src',
     paths:
      { '*': [Array],
        '@': [Array],
        '@/*': [Array],
        '@/mhy': [Array],
        '@/mhy/*': [Array] },
     typeRoots:
      [ '/path/redacted/node_modules/mhy/node_modules/@types',
        '/path/redacted/node_modules/@types' ] },
  include:
   [ '/path/redacted/src/**/*' ],
  files:
   [ '/path/redacted/node_modules/mhy/dist/configs/typescript/mhy.d.ts' ] }
```

Notice how the paths contain `[Array]` only.

Not sure if this is by design, but IMHO there could be a depth flag similar to node's [`util.inspect()`](https://nodejs.org/api/util.html#util_util_inspect_object_options). For example `--depth 0` or just no depth flag should print the full object (this would change the default behaviour of the command though).

WDYT?

**Comment by wintercounter** [comment]
`mhy config typescript -f json`

What I wanted always is to add a flag where i can specify only a certain path to be printed. eg `compilerOptions.module`. With really deep stuff (like webpack config) it would be really useful.

**Comment by FabianLauer** [comment]
> mhy config typescript -f json

👍 Missed that in the docs, sorry. 

And agreed on printing a path only. Talking about that, cli parameter autocompletion would be very convenient for this.

**Comment by wintercounter** [comment]
mhy uses `yargs` which supports it, shouldn't be a big deal to add support for it. I'm adding it to the continous todo list.

**Comment by wintercounter** [comment]
Added flag `-p,--path` in 4.0.0. `d` was already taken.
