### ISSUE TITLE
Dashboard UI : scroll in a box makes it not responding (or too slow to respond) (mac os)

### ISSUE THREAD

**Issue by thomaswinckell** [wintercounter/mhy#4]
In the dashboard UI, when I scroll in a box, it makes the dashboard not responding, or too slow (like at least 10 seconds).

I am not mac os and I use iTerm2. I tested using Terminal also, it's the same.

**Comment by thomaswinckell** [comment]
One solution could be to disable the scrolling on the box, since it's not working well. I have seen a scrollable prop set to true. @wintercounter If you want to go for it, I can test this and submit a pull request.

**Comment by wintercounter** [comment]
Scrolling needs to be there and with arrows it works well. We need another solution where mousewheel won't mess it up. Actually maybe it is conflicting with the build-in scroll. `mouse={false}` can be tried as an alternative.
